/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report minimal liveness publicly, details only when authorized.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Leads
         * @description Run the customer-mode pipeline for a product offer.
         *
         *     Body validation runs before this handler, so invalid (422) requests never
         *     consume rate-limit quota. The feature flag is checked before the
         *     access-code gate so a disabled mode stays silent.
         */
        post: operations["api_leads_api_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outreach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Outreach
         * @description Draft a short outreach message for a profile/target pair.
         */
        post: operations["api_outreach_api_outreach_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Search
         * @description Run the full search pipeline for a user profile.
         *
         *     Body validation runs before this handler, so invalid (422) requests never
         *     consume rate-limit quota. The access-code check stays first.
         */
        post: operations["api_search_api_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CityCenter
         * @description Approximate map centre for the searched city (geocoded, cached).
         */
        CityCenter: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /**
         * ForumItem
         * @description A relevant discussion found in an online forum.
         */
        ForumItem: {
            /** Link */
            link: string;
            /** Snippet */
            snippet: string;
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Job
         * @description A job result returned from a search source.
         */
        Job: {
            /** Company */
            company: string;
            /** Desc */
            desc: string;
            /** Flags */
            flags: string[];
            /** Geo Precision */
            geo_precision?: ("city" | "approximate") | null;
            /** Lat */
            lat?: number | null;
            /** Link */
            link?: string | null;
            /** Lng */
            lng?: number | null;
            /** Location */
            location: string;
            /**
             * Risk
             * @enum {string}
             */
            risk: "Low" | "Medium" | "High";
            /** Salary */
            salary?: string | null;
            /** Title */
            title: string;
            /**
             * Via
             * @default
             */
            via: string;
        };
        /**
         * Lead
         * @description One candidate customer business. Scores are signals, not guarantees.
         */
        Lead: {
            /** Address */
            address?: string | null;
            /** Adjustments */
            adjustments?: string[];
            /** Business Type */
            business_type?: string | null;
            /**
             * Likely Has Software
             * @default false
             */
            likely_has_software: boolean;
            /** Maps Url */
            maps_url?: string | null;
            /** Match Reasons */
            match_reasons: string[];
            /** Match Score */
            match_score: number;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            /** Pitch Angle */
            pitch_angle?: string | null;
            /** Price Level */
            price_level?: number | null;
            /** Rating */
            rating?: number | null;
            /** Research Notes */
            research_notes?: string | null;
            /** Score Breakdown */
            score_breakdown?: {
                [key: string]: number;
            };
            /** Suggested First Question */
            suggested_first_question?: string | null;
            /** User Ratings Total */
            user_ratings_total?: number | null;
            /** Why Fit */
            why_fit?: string | null;
        };
        /**
         * LeadMeta
         * @description Credits, cache, degradation and per-stage timings for a leads request.
         */
        LeadMeta: {
            /** Cache Hits */
            cache_hits: number;
            /** Credits Used */
            credits_used: number;
            /**
             * Degraded
             * @default []
             */
            degraded: string[];
            /**
             * Notes
             * @default []
             */
            notes: string[];
            /**
             * Partial
             * @default []
             */
            partial: string[];
            /**
             * Timings Ms
             * @default {}
             */
            timings_ms: {
                [key: string]: number;
            };
        };
        /**
         * LeadsResponse
         * @description Ranked customer leads plus honesty metadata.
         */
        LeadsResponse: {
            /**
             * Disclaimer
             * @default Lead scores are signals from public data, not guarantees. Verify details before contacting.
             */
            disclaimer: string;
            /** Leads */
            leads: components["schemas"]["Lead"][];
            /** Market Notes */
            market_notes: string[];
            meta: components["schemas"]["LeadMeta"];
            /** Offer Summary */
            offer_summary: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
        };
        /**
         * Meta
         * @description Request metadata returned alongside search results.
         */
        Meta: {
            city_center?: components["schemas"]["CityCenter"] | null;
            /** Degraded */
            degraded: string[];
            /** Duration Ms */
            duration_ms: number;
            /**
             * Notes
             * @default []
             */
            notes: string[];
            /**
             * Partial
             * @default []
             */
            partial: string[];
            /** Request Id */
            request_id: string;
        };
        /**
         * OfferInput
         * @description Owner-supplied product description plus targeting parameters.
         */
        OfferInput: {
            /** City */
            city: string;
            /**
             * Max Leads
             * @default 10
             */
            max_leads: number;
            /** Monthly Price */
            monthly_price?: number | null;
            /** Offer */
            offer: string;
        };
        /**
         * Opportunity
         * @description Validated final earning opportunity with scores and supporting evidence.
         */
        Opportunity: {
            /**
             * Adjustments
             * @default []
             */
            adjustments: string[];
            /** Competition */
            competition: number;
            /** Cost Ease */
            cost_ease: number;
            /** Demand */
            demand: number;
            /** Earn Score */
            earn_score: number;
            /** Evidence */
            evidence: string[];
            /** Fit */
            fit: number;
            /** Income Estimate */
            income_estimate: string;
            /** Plan 7 Days */
            plan_7_days: string[];
            /** Score Breakdown */
            score_breakdown: {
                [key: string]: number;
            };
            /** Title */
            title: string;
            /** Trust */
            trust: number;
            /**
             * Type
             * @enum {string}
             */
            type: "job" | "freelance" | "local business" | "online selling" | "content";
            /** Why */
            why: string;
        };
        /**
         * OutreachRequest
         * @description Inputs for creating a message tailored to an opportunity target.
         */
        OutreachRequest: {
            profile: components["schemas"]["Profile"];
            /** Target */
            target: {
                [key: string]: unknown;
            };
        };
        /**
         * OutreachResponse
         * @description Generated outreach message plus a fixed safety note.
         */
        OutreachResponse: {
            /** Message */
            message: string;
            /** Safety Note */
            safety_note: string;
        };
        /**
         * Place
         * @description A local business or service provider search result.
         */
        Place: {
            /** Address */
            address?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            /** Rating */
            rating?: number | null;
            /** Reviews */
            reviews?: number | null;
            /** Type */
            type?: string | null;
        };
        /**
         * Profile
         * @description User profile parameters used to tailor earning recommendations.
         */
        Profile: {
            /**
             * Budget
             * @default 0
             */
            budget: number;
            /** City */
            city: string;
            /**
             * Hours
             * @default 10
             */
            hours: number;
            /** Skills */
            skills: string;
        };
        /**
         * SearchResponse
         * @description Complete response containing recommendations and supporting source data.
         */
        SearchResponse: {
            /** Forum */
            forum: components["schemas"]["ForumItem"][];
            /** Jobs */
            jobs: components["schemas"]["Job"][];
            /** Local */
            local: components["schemas"]["Place"][];
            meta: components["schemas"]["Meta"];
            /** Opportunities */
            opportunities: components["schemas"]["Opportunity"][];
            stats: components["schemas"]["Stats"];
            /** Trend */
            trend: components["schemas"]["TrendPoint"][];
            /** Trend Growth */
            trend_growth: {
                [key: string]: number;
            };
            /** Trend Keyword */
            trend_keyword: string | null;
        };
        /**
         * Stats
         * @description Usage and cache statistics for a response.
         */
        Stats: {
            /** Cache Hits */
            cache_hits: number;
            /** Credits Used */
            credits_used: number;
        };
        /**
         * TrendPoint
         * @description A dated trend measurement.
         */
        TrendPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_leads_api_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_outreach_api_outreach_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutreachRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutreachResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_search_api_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Profile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
